---
- name: MariaDB server is running
  hosts: database_dev
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
      - httpd
    db_services:
      - mariadb
      - httpd
  tasks:
    - name: MariaDB packages are installed
      yum:
        name: "{{ mariadb_packages }}"
        state: present 
#      loop: "{{ mariadb_packages }}"
      when: ansible_distribution == "RedHat"

      ## NOTE: Using the SYSTEMD module instead of SERVICE module
    - name: Start MariaDB service
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ db_services }}"
